extensions:
    pim-variant-group-index:
        module: pim/form/common/index/index
        config:
            title: pim_enrich.index.variant_group.title

    pim-variant-group-edit-form-breadcrumbs:
        module: pim/common/breadcrumbs
        parent: pim-variant-group-edit-form
        targetZone: breadcrumbs
        config:
            path:
                - pim-menu-system
                - pim-menu-system-variant-group

    pim-variant-group-index-grid:
        module: pim/form/common/index/grid
        parent: pim-variant-group-index
        position: 1000
        targetZone: content
        config:
            alias: variant-group-grid

    pim-variant-group-index-create-button:
        module: pim/form/common/index/create-button
        parent: pim-variant-group-index
        targetZone: buttons
        position: 100
        aclResourceId: pim_enrich_variant_group_create
        config:
           iconName:  plus
           title:     pim_enrich.index.variant_group.create_btn
           url:       pim_enrich_variant_group_create
