parameters:
    pim_datagrid.datasource.result_record.hydrator.object_id.class:          Pim\Bundle\DataGridBundle\Datasource\ResultRecord\Orm\ObjectIdHydrator
    pim_datagrid.datasource.result_record.hydrator.object.class:             Pim\Bundle\DataGridBundle\Datasource\ResultRecord\Orm\ObjectHydrator
